# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Agnostic Security Ltd
"""`/api/show` synthesis — ollama's single-model detail response.

Envelope parity target (`tests/fixtures/ollama-golden/show.json`, captured
verbatim from a real ollama): the top-level field set is exactly

    {capabilities, details, license, model_info, modelfile,
     modified_at, system, template, tensors}

Every one of those keys is emitted byte-PRESENT here (never omitted), even
when the source GGUF carries no value for it — an omitted key is a silent
parity break for any ollama client that indexes the field directly, exactly
the class of bug the `/api/tags` `capabilities`/`details` fixes closed. The
extra `parameters` key the shim used to emit is dropped: real ollama only
surfaces `parameters` when a Modelfile defines `PARAMETER` lines, and it is
absent from this envelope's golden shape.
"""

from __future__ import annotations

from typing import Any

from kuroshio.gguf.header import GGUFParseError, parse_gguf_header
from kuroshio.gguf.quant_types import ggml_type_name
from kuroshio.models import ResolvedModel
from kuroshio.shim.tags import capabilities_list, details_dict


def _tensor_metadata(model: ResolvedModel) -> list[dict[str, Any]]:
    """`tensors[]` — one ``{name, type, shape}`` entry per GGUF tensor, mirroring
    ollama's `/api/show` `tensors` array.

    Re-parses the tensor-info table from the already-admitted, content-addressed
    blob at serve time (an infrequent admin call). The bytes are our own store's
    (jailed at admission — see `SourceAdapter._first_parse_gguf_header`), so this
    read is trusted; it still fails SOFT — a blob that will not re-parse yields an
    empty list rather than 500-ing the endpoint, since `model_info`/`details`
    already carry the displayable metadata.
    """
    try:
        header = parse_gguf_header(model.blob_path, parse_tensors=True)
    except (GGUFParseError, OSError):
        return []
    return [
        {
            "name": tensor.name,
            "type": ggml_type_name(tensor.ggml_type),
            "shape": list(tensor.dimensions),
        }
        for tensor in header.tensors
    ]


def synthesize_show(model: ResolvedModel) -> dict[str, Any]:
    """Build the `/api/show` response body for one model, in envelope parity with
    ollama's golden field set."""
    metadata = model.metadata
    return {
        "modelfile": "# generated by yashigani-kuroshio ollama-shim\n",
        # `template` is the GGUF-embedded `tokenizer.chat_template`, extracted at
        # adapt time (Red-Council H4) and carried on the normalized metadata — no
        # re-parse needed. Byte-present ("" when the GGUF lacked one).
        "template": metadata.get("chat_template") or "",
        "details": details_dict(model),
        "model_info": dict(metadata),
        "modified_at": model.provenance.recorded_at.isoformat(),
        # Same derivation rule as `/api/tags`: honour metadata-declared caps, else
        # fall back to the universally-true ["completion"] — never over-claim
        # tools/vision we cannot verify from the GGUF header.
        "capabilities": capabilities_list(model),
        # `license` / `system` are Modelfile-level fields in ollama; a raw GGUF
        # import carries neither the full licence TEXT nor a SYSTEM prompt (only a
        # short `general.license` id lives in model_info). We honour any value the
        # adapter did normalize onto the metadata, else emit ollama's empty shape
        # ("") byte-present rather than dropping the key.
        "license": metadata.get("license") or "",
        "system": metadata.get("system") or "",
        "tensors": _tensor_metadata(model),
    }


__all__ = ["synthesize_show"]
