# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Agnostic Security Ltd
"""`/api/show` synthesis — ollama's single-model detail response."""

from __future__ import annotations

from typing import Any

from yashigani_infer.models import ResolvedModel
from yashigani_infer.shim.tags import details_dict


def synthesize_show(model: ResolvedModel) -> dict[str, Any]:
    """Build the `/api/show` response body for one model."""
    return {
        "modelfile": "# generated by yashigani-infer ollama-shim\n",
        "parameters": "",
        "template": "",
        "details": details_dict(model),
        "model_info": dict(model.metadata),
        "modified_at": model.provenance.recorded_at.isoformat(),
    }


__all__ = ["synthesize_show"]
