"""v2.24.1 — LU-AMEND-01 wave-3: bigserial sequence column on audit_events.

Revision ID: 0014
Revises: 0013
Create Date: 2026-05-25

Rationale (LU-AMEND-01 wave-3 specification):
    Wave-2 (migration 0011) established the hash chain (prev_hash + event_hash).
    However, the chain-row ordering used (created_at, id) is non-deterministic
    under timestamp collision (two events inserted at the same microsecond yield
    UUID v4 sort order, which is random per-replica). This weakens the hash-
    chain integrity guarantee under high-throughput: checkpoint computation on
    replica A may disagree with replica B.

    This migration closes the gap by adding a BIGSERIAL ``seq`` column that
    provides a strictly monotonic, database-assigned ordering key. The seq
    column becomes the AUTHORITATIVE ordering for:
      - prev_hash lookup in AuditChainService.compute_hashes_for_event()
      - daily merkle-root checkpoint in AuditChainService.run_daily_checkpoint()

    All future INSERTs automatically receive a unique seq (BIGSERIAL default).
    Existing rows (seq IS NULL) are backfilled in a single UPDATE ordered by
    (created_at, id) — preserving the ordering that was used in wave-2 so that
    existing chain verification remains valid.

    Compliance mapping:
      ASVS V7.3.3  — audit log integrity (tamper-evident)
      NIST AU-9    — protection of audit information
      NIST AU-10   — non-repudiation (deterministic chain ordering)
      SOC 2 CC7.2  — monitoring + evaluation of security events

Design notes:
  - BIGSERIAL = BIGINT + explicit sequence; PostgreSQL-specific. MySQL
    equivalent would be AUTO_INCREMENT BIGINT. For now, Yashigani is single-PG.
  - seq NOT NULL; no UNIQUE constraint at the DB level — audit_events is
    PARTITION BY RANGE (created_at); PG requires UNIQUE constraints on
    partitioned tables to include all partitioning columns (i.e., UNIQUE
    would need to be (seq, created_at)). The sequence object itself guarantees
    monotonic non-repeating values; we document this as an accepted limitation.
  - BIGSERIAL sequences are NOT transactionally rolled back on INSERT error —
    a failed INSERT advances the sequence (gap-safe). Chain integrity relies on
    strict monotonic order, not on contiguous seq values.
  - Backfill uses a CTE to assign deterministic seq values via ROW_NUMBER()
    ordered by (created_at, id) for NULL-seq rows. This preserves wave-2 ordering.
  - Forward-only: no downgrade path (sequences are append-only; reversing the
    column would leave orphaned seq references in the chain). Downgrade raises.

Evidence artefact: reference this migration SHA in the v2.24.1 compliance pack
for LU-AMEND-01 wave-3 closure.

Last updated: 2026-05-25T00:00:00+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0014"
down_revision: Union[str, None] = "0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_DDL_UP = """
-- ================================================================
-- LU-AMEND-01 wave-3: bigserial sequence column on audit_events
-- ================================================================

-- Note on partitioned-table UNIQUE constraints (PostgreSQL):
--   audit_events is PARTITION BY RANGE (created_at).  PostgreSQL requires
--   that UNIQUE constraints on partitioned tables include ALL partitioning
--   columns (PG ERROR: "unique constraint on partitioned table must include
--   all partitioning columns").  A plain UNIQUE(seq) is therefore not
--   enforceable at the DB level.
--
--   This is acceptable: seq is generated by a single global BIGSERIAL
--   sequence object (audit_events_seq_seq) which guarantees strict
--   monotonic non-repeating values at the database level via the sequence
--   mechanism.  Application-level uniqueness is guaranteed by the sequence
--   itself; the formal UNIQUE constraint is a belt-and-suspenders check
--   that PG cannot enforce across partition boundaries without including
--   the partition key.  We document this as an accepted limitation.
--
--   Index strategy: use plain B-tree indexes (not UNIQUE-constraint indexes)
--   on seq alone and (tenant_id, seq) for checkpoint query performance.
--   These indexes do not enforce uniqueness but do enable ORDER BY seq.

-- Step 1: Create the explicit sequence.
CREATE SEQUENCE IF NOT EXISTS audit_events_seq_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Step 2: Add the seq column as nullable BIGINT with the sequence as default.
-- Nullable to allow backfill of existing rows before applying NOT NULL.
ALTER TABLE audit_events
    ADD COLUMN IF NOT EXISTS seq BIGINT DEFAULT nextval('audit_events_seq_seq');

-- Step 3: Backfill existing rows that have seq IS NULL (pre-migration rows).
-- We assign seq values ordered by (created_at, id) — same ordering that
-- wave-2 chain verification used — so that existing chain hashes remain
-- valid under the new seq-based ordering key.
-- ROW_NUMBER() gives a stable 1-based assignment over the ordered rows.
-- setval() advances the sequence past the highest backfilled value so
-- future INSERTs receive seq values strictly greater than all backfilled rows.
DO $$
DECLARE
    max_seq BIGINT;
BEGIN
    SELECT COUNT(*) INTO max_seq FROM audit_events WHERE seq IS NULL;

    IF max_seq > 0 THEN
        WITH numbered AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn
            FROM audit_events
            WHERE seq IS NULL
        )
        UPDATE audit_events ae
        SET seq = n.rn
        FROM numbered n
        WHERE ae.id = n.id;

        -- Advance the sequence past the highest backfilled value.
        -- is_called=false means the NEXT call returns exactly max_seq+1.
        PERFORM setval('audit_events_seq_seq', max_seq + 1, false);
    END IF;
END;
$$;

-- Step 4: Apply NOT NULL after backfill is complete.
-- No UNIQUE constraint here — see note above on partitioned tables.
ALTER TABLE audit_events
    ALTER COLUMN seq SET NOT NULL;

-- Step 5: B-tree index on seq for ORDER BY seq NULLS LAST queries.
CREATE INDEX IF NOT EXISTS idx_audit_events_seq
    ON audit_events (seq);

-- Step 6: Composite index on (tenant_id, seq) for per-tenant checkpoint query.
CREATE INDEX IF NOT EXISTS idx_audit_events_tenant_seq
    ON audit_events (tenant_id, seq);

-- Step 7: Grant USAGE + SELECT on the sequence to yashigani_app so INSERTs
-- via the app role can advance the sequence (nextval).
GRANT USAGE, SELECT ON SEQUENCE audit_events_seq_seq TO yashigani_app;
"""

# Downgrade is intentionally a hard failure: sequences are append-only and
# the chain ordering guarantee depends on seq being present. Rolling back
# would silently break chain integrity on any rows inserted after the upgrade.
_DDL_DOWN_MESSAGE = """
DO $$
BEGIN
    RAISE EXCEPTION
        'Migration 0014 downgrade is not supported. '
        'The bigserial seq column on audit_events provides the authoritative '
        'ordering key for the hash chain (LU-AMEND-01 wave-3). Removing it '
        'would silently break chain integrity for all rows inserted after '
        'the upgrade. If you must rollback, restore from a pre-0014 backup.';
END;
$$;
"""


def upgrade() -> None:
    op.execute(_DDL_UP)


def downgrade() -> None:
    # Fail closed — see _DDL_DOWN_MESSAGE rationale above.
    op.execute(_DDL_DOWN_MESSAGE)
