"""4.0 — Chat persistence: conversations + messages tables.

Revision ID: 0024
Revises: 0023
Create Date: 2026-06-27

Rationale:
    Yashigani 4.0 replaces OpenWebUI (OWUI) with a fully-owned user chat
    backend.  Previously OWUI kept its own SQLite/Postgres DB for conversation
    history; after the transition Yashigani must persist chat history itself.

    Two tables:

      conversations  — one row per user chat session; scoped to account_id
                       (the authenticated user's session.account_id).  Title
                       is set by the user and defaults to 'New conversation'.

      messages       — one row per chat message; linked to a conversation via
                       a FK with ON DELETE CASCADE so deleting a conversation
                       removes all its messages atomically.  Stores role
                       (user/assistant/system), content, model used for
                       assistant turns, plus optional token_count + verdict
                       JSONB for OPA/classification metadata.

    BOLA (OWASP API3): all application-layer queries scope by account_id in
    the WHERE clause.  There is intentionally NO database-level RLS here — the
    application enforces isolation via ``WHERE id = $1 AND account_id = $2``
    and returns 404 on mismatch (never 403 — to avoid leaking existence).

    Least-priv (mirrors 0015 / 0022 pattern):
      yashigani_app gets SELECT, INSERT, UPDATE, DELETE on both tables.
      UUID PKs are generated by gen_random_uuid() (Postgres 13+ built-in,
      no extension required), so no sequence grants are needed.

    Index design:
      idx_conversations_account  — (account_id, updated_at DESC): the primary
                                   list query paginates a user's conversations
                                   newest-first.
      idx_messages_conversation  — (conversation_id, created_at ASC): the
                                   primary thread-fetch query returns messages
                                   in chronological order.

Downgrade: drops both tables (CASCADE removes indexes and FK constraints).
"""
# Last updated: 2026-06-27T00:00:00+00:00
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0024"
down_revision: Union[str, None] = "0023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_DDL_UP = """
-- ================================================================
-- 4.0 Chat persistence
-- ================================================================

CREATE TABLE conversations (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id  TEXT        NOT NULL,
    title       TEXT        NOT NULL DEFAULT 'New conversation',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- List query: user's conversations ordered newest-first.
CREATE INDEX idx_conversations_account
    ON conversations (account_id, updated_at DESC);

CREATE TABLE messages (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID        NOT NULL
        REFERENCES conversations(id) ON DELETE CASCADE,
    role            TEXT        NOT NULL
        CHECK (role IN ('user', 'assistant', 'system')),
    content         TEXT        NOT NULL DEFAULT '',
    model           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    token_count     INTEGER,
    verdict         JSONB
);

-- Thread-fetch query: messages for a conversation in chronological order.
CREATE INDEX idx_messages_conversation
    ON messages (conversation_id, created_at ASC);

-- ================================================================
-- Least-priv (mirrors 0022 / 0015)
-- UUID PKs use gen_random_uuid() — no sequence to grant.
-- ================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON conversations TO yashigani_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON messages     TO yashigani_app;
"""

_DDL_DOWN = """
DROP TABLE IF EXISTS messages      CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
"""


def upgrade() -> None:
    op.execute(_DDL_UP)


def downgrade() -> None:
    op.execute(_DDL_DOWN)
