"""4.0 — User-plane durable store: user_agents, user_memory_blocks,
user_agent_memory_links, user_workflows.

Revision ID: 0025
Revises: 0024
Create Date: 2026-06-27

Rationale:
    ua:* and wf:* keys in Redis db/3 run with NO persistence
    (appendonly no / save ""). A Redis db/3 wipe (container recreate,
    volume deletion) loses all user agents, memory blocks, memory-block
    attachment records, and workflow definitions with zero operator signal.

    This migration extends the existing AgentRegistry durable-mirror pattern
    (migration 0017 + durable_store.py) to the user-plane stores.

    Four tables:

      user_agents            — one row per user agent; ua_id unique PK.
                               Stores metadata + personality/skills JSONB +
                               optional Langflow/NHI columns.
                               BOLA column: account_id (app-layer; no RLS).

      user_memory_blocks     — one row per user memory block; block_id unique PK.
                               Stores label + value + optional letta_block_id.
                               BOLA column: account_id (app-layer; no RLS).

      user_agent_memory_links — join table for the many-to-many attachment
                               relationship between ua:meta and ua:mem:meta.
                               Cascades: deleting an agent or block removes
                               its links atomically.

      user_workflows         — one row per committed workflow; wf_id unique PK.
                               Stores name, spec JSONB, enabled flag, schedule.
                               BOLA column: account_id (app-layer; no RLS).

    BOLA design (OWASP API3):
      There is intentionally NO database-level RLS on these tables. Application
      code enforces isolation via ``WHERE ua_id = $1 AND account_id = $2``
      (or the equivalent) and returns 404 on mismatch to avoid leaking
      resource existence. This mirrors the conversations/messages tables in
      migration 0023.

    Least-priv (mirrors 0023 / 0022 / 0015 pattern):
      yashigani_app gets SELECT, INSERT, UPDATE, DELETE on all four tables.
      UUID PKs are generated by gen_random_uuid() (Postgres 13+ built-in,
      no extension required), so no sequence grants are needed.

    Index design:
      idx_user_agents_account              — (account_id)
      idx_user_memory_blocks_account       — (account_id)
      idx_user_workflows_account           — (account_id)

Downgrade: drops all four tables in reverse dependency order (CASCADE
  removes FK constraints and indexes automatically).
"""
# Last updated: 2026-06-27T00:00:00+00:00
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0025"
down_revision: Union[str, None] = "0024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_DDL_UP = """
-- ================================================================
-- 4.0 User-plane durable store
-- ISSUE-USER-PLANE-DURABILITY
-- ================================================================

CREATE TABLE user_agents (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id       TEXT        NOT NULL,
    ua_id            TEXT        NOT NULL UNIQUE,
    name             TEXT        NOT NULL DEFAULT '',
    description      TEXT        NOT NULL DEFAULT '',
    alias            TEXT        NOT NULL DEFAULT '',
    kind             TEXT        NOT NULL DEFAULT 'agent',
    personality      JSONB,
    effective_skills JSONB,
    declared_skills  JSONB,
    graph            TEXT,
    graph_hash       TEXT,
    letta_agent_id   TEXT,
    nhi_id           TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_agents_account ON user_agents (account_id);

CREATE TABLE user_memory_blocks (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id     TEXT        NOT NULL,
    block_id       TEXT        NOT NULL UNIQUE,
    label          TEXT        NOT NULL DEFAULT '',
    value          TEXT        NOT NULL DEFAULT '',
    letta_block_id TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_memory_blocks_account ON user_memory_blocks (account_id);

CREATE TABLE user_agent_memory_links (
    ua_id    TEXT NOT NULL REFERENCES user_agents(ua_id)        ON DELETE CASCADE,
    block_id TEXT NOT NULL REFERENCES user_memory_blocks(block_id) ON DELETE CASCADE,
    PRIMARY KEY (ua_id, block_id)
);

CREATE TABLE user_workflows (
    id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id        TEXT        NOT NULL,
    wf_id             TEXT        NOT NULL UNIQUE,
    owner_identity_id TEXT        NOT NULL DEFAULT '',
    name              TEXT        NOT NULL DEFAULT '',
    description       TEXT        NOT NULL DEFAULT '',
    spec              JSONB,
    spec_hash         TEXT,
    enabled           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_workflows_account ON user_workflows (account_id);

-- ================================================================
-- Least-priv (mirrors 0023 / 0022 / 0015)
-- UUID PKs use gen_random_uuid() — no sequence to grant.
-- ================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON user_agents             TO yashigani_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON user_memory_blocks      TO yashigani_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON user_agent_memory_links TO yashigani_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON user_workflows          TO yashigani_app;
"""

_DDL_DOWN = """
DROP TABLE IF EXISTS user_agent_memory_links CASCADE;
DROP TABLE IF EXISTS user_memory_blocks      CASCADE;
DROP TABLE IF EXISTS user_agents             CASCADE;
DROP TABLE IF EXISTS user_workflows          CASCADE;
"""


def upgrade() -> None:
    op.execute(_DDL_UP)


def downgrade() -> None:
    op.execute(_DDL_DOWN)
