#!/usr/bin/env bash
# scripts/offboard.sh — yashigani offboard <agent-name>
#
# Reverses the codegen output for a named onboarded agent:
#   1. Removes the service_identities.yaml entry (sentinel-guarded)
#   2. Removes the pki_ownership.sh tuple (sentinel-guarded, via Python rewriter)
#   3. Removes the Caddy include LINE from docker/caddy/agents/ (include line only —
#      does NOT restructure Caddyfile internals; S4 sentinel-insert is Captain's scope)
#   4. Removes the compose override stanza (docker/<agent>-compose.override.yml)
#   5. Wipes secrets/certs: <agent>_client.{key,crt}
#   6. Triggers _pki_run_issuer rotate-leaves to rotate remaining service leaves
#   7. Removes the Helm values block (values-<agent>.yaml + networkpolicy overlay)
#   8. Writes an offboard ledger entry (docker/var/offboard-ledger.log)
#
# Each step is idempotent — safe to re-run if a previous run was interrupted.
#
# S4 TODO (Captain scope): Caddyfile sentinel-insert/remove for the import line
# lives in the Captain parallel branch (feat/p1-w3p2a-caddy-hardening). This
# script removes the include FILE (agents/<agent>.caddy) and the import LINE
# within whichever Caddyfile contains it, using an exact-string match. Do NOT
# restructure Caddyfile blocks or change the surrounding block layout.
#
# Security:
#   - Three-tier file removal: direct → podman unshare → ephemeral container
#     (mirrors uninstall.sh pattern, avoid EPERM on UID-remapped secrets)
#   - Never uses sed -i (BSD/GNU portability trap)
#   - Fail-closed: any required step failing exits non-zero
#   - Idempotent: re-running after partial completion is safe
#
# Usage:
#   ./scripts/offboard.sh <agent-name>
#   YSG_RUNTIME=docker ./scripts/offboard.sh my-agent
#   YSG_DRY_RUN=true ./scripts/offboard.sh my-agent
#
# Requirements:
#   - Run from the repo root (or WORK_DIR set)
#   - install.sh must have been run previously (WORK_DIR must exist)
#   - python3 available for lib/pki_ownership_append.py calls
#
# Bash 3.2 compatibility: no declare -A, no ${var,,}, no mapfile.
#
# Last updated: 2026-05-29T00:00:00+00:00 (feat(p1-w4): S5 yashigani offboard command)
# ---------------------------------------------------------------------------

set -euo pipefail
IFS=$(printf '\n\t')

# Hardened PATH — never trust inherited PATH for privileged scripts.
PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/podman/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH

# ---------------------------------------------------------------------------
# Globals
# ---------------------------------------------------------------------------
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_REPO_ROOT="$(cd "${_SCRIPT_DIR}/.." && pwd)"

WORK_DIR="${WORK_DIR:-${_REPO_ROOT}}"
YSG_RUNTIME="${YSG_RUNTIME:-}"
YSG_DRY_RUN="${YSG_DRY_RUN:-false}"

# Alpine image for ephemeral-container tier (digest-pinned, same as install.sh).
_ALPINE_IMAGE="alpine:3@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11"

# ---------------------------------------------------------------------------
# Logging helpers (mirror install.sh style)
# ---------------------------------------------------------------------------
_log_info()  { printf "  [offboard] %s\n"        "$*"; }
_log_warn()  { printf "  [offboard] WARN: %s\n"  "$*" >&2; }
_log_error() { printf "  [offboard] ERROR: %s\n" "$*" >&2; }
_log_step()  { printf "\n  [offboard] ── %s\n"   "$*"; }
_dry_print() {
  if [[ "${YSG_DRY_RUN:-false}" == "true" ]]; then
    printf "  [DRY-RUN] %s\n" "$*"
    return 0
  fi
  return 1  # not dry run — caller should execute the real command
}

# ---------------------------------------------------------------------------
# _offboard_usage
# ---------------------------------------------------------------------------
_offboard_usage() {
  cat >&2 <<'USAGE'
Usage: scripts/offboard.sh <agent-name>

  Removes all artifacts generated by `yashigani onboard` for the named agent:
    service_identities.yaml entry, pki_ownership.sh tuple, Caddy snippet,
    compose override, certs/keys, Helm values, and writes an offboard ledger entry.

Options (env vars):
  YSG_RUNTIME=docker|podman    — override runtime detection
  YSG_DRY_RUN=true             — print actions without executing
  WORK_DIR=/path/to/repo       — override repo root

USAGE
  exit 1
}

# ---------------------------------------------------------------------------
# _validate_agent_name — reject names with shell metacharacters
# ---------------------------------------------------------------------------
_validate_agent_name() {
  local _name="$1"
  if ! printf '%s' "$_name" | grep -qE '^[A-Za-z0-9_-]+$'; then
    _log_error "agent name '${_name}' contains illegal characters; only [A-Za-z0-9_-] permitted."
    return 1
  fi
}

# ---------------------------------------------------------------------------
# _detect_runtime — resolve YSG_RUNTIME if not set
# Source W2 detect_runtime.sh if available; fall back to legacy YSG_RUNTIME.
# ---------------------------------------------------------------------------
_offboard_detect_runtime() {
  if [[ -n "${YSG_RUNTIME:-}" ]]; then
    _log_info "Runtime: ${YSG_RUNTIME} (explicit)"
    return 0
  fi
  # Source W2 detect_runtime.sh for 4-way detection
  local _dr_sh="${_REPO_ROOT}/lib/detect_runtime.sh"
  if [[ -f "$_dr_sh" ]]; then
    # shellcheck source=lib/detect_runtime.sh
    # shellcheck disable=SC1091
    . "$_dr_sh"
    _detect_runtime 2>/dev/null || true
    case "${YSG_RUNTIME_4WAY:-unknown}" in
      docker)           YSG_RUNTIME="docker" ;;
      podman-rootful)   YSG_RUNTIME="podman" ;;
      podman-rootless)  YSG_RUNTIME="podman" ;;
      k8s)              YSG_RUNTIME="k8s"    ;;
      *)
        _log_warn "Could not detect runtime — defaulting to docker. Set YSG_RUNTIME explicitly."
        YSG_RUNTIME="docker"
        ;;
    esac
  else
    _log_warn "lib/detect_runtime.sh not found — defaulting to docker."
    YSG_RUNTIME="docker"
  fi
  _log_info "Runtime detected: ${YSG_RUNTIME} (YSG_RUNTIME_4WAY=${YSG_RUNTIME_4WAY:-n/a})"
}

# ---------------------------------------------------------------------------
# _runtime_cmd — return the container runtime command name
# ---------------------------------------------------------------------------
_offboard_runtime_cmd() {
  case "${YSG_RUNTIME:-docker}" in
    podman) printf 'podman' ;;
    docker) printf 'docker' ;;
    k8s)    printf 'kubectl' ;;
    *)      printf 'docker' ;;
  esac
}

# ---------------------------------------------------------------------------
# _three_tier_rm — remove a file with three-tier fallback
#   Tier 1: direct rm (same-user / root caller)
#   Tier 2: podman unshare rm (rootless Podman path)
#   Tier 3: ephemeral container rm (Docker or Podman remote)
#
# Usage: _three_tier_rm <file-path>
# Returns: 0 on success, 1 on total failure
# ---------------------------------------------------------------------------
_three_tier_rm() {
  local _target="$1"
  if [[ ! -e "$_target" ]]; then
    _log_info "  (already absent: ${_target})"
    return 0
  fi

  if _dry_print "rm -f ${_target}"; then
    return 0
  fi

  # Tier 1: direct
  if rm -f "$_target" 2>/dev/null; then
    _log_info "  [removed tier-1] ${_target}"
    return 0
  fi

  _log_warn "  direct rm failed for ${_target} — trying tier-2 (podman unshare)"

  # Tier 2: podman unshare (rootless Podman path)
  if command -v podman >/dev/null 2>&1; then
    if podman unshare rm -f "$_target" 2>/dev/null; then
      _log_info "  [removed tier-2] ${_target} (podman unshare)"
      return 0
    fi
    _log_warn "  podman unshare rm failed — trying tier-3 (ephemeral container)"
  fi

  # Tier 3: ephemeral container
  local _runtime
  _runtime="$(_offboard_runtime_cmd)"
  local _parent
  _parent="$(dirname "$_target")"
  local _basename
  _basename="$(basename "$_target")"
  if "${_runtime}" run --rm \
      -v "${_parent}:/t:rw,Z" \
      "$_ALPINE_IMAGE" rm -f "/t/${_basename}" 2>/dev/null; then
    _log_info "  [removed tier-3] ${_target} (ephemeral container)"
    return 0
  fi

  _log_error "  All three removal tiers failed for: ${_target}"
  _log_error "  Manual cleanup required:"
  _log_error "    rm -f '${_target}'"
  _log_error "    OR: podman unshare rm -f '${_target}'"
  return 1
}

# ---------------------------------------------------------------------------
# Step 1: Remove service_identities.yaml entry
# The entry is bracketed by sentinel comments:
#   # BEGIN YSG-ONBOARD-<agent>
#   ...
#   # END YSG-ONBOARD-<agent>
# Uses Python rewriter (same approach as lib/pki_ownership_append.py)
# to avoid BSD vs GNU sed portability issues.
# ---------------------------------------------------------------------------
_offboard_step1_service_identity() {
  local _agent="$1"
  local _sid_file="${WORK_DIR}/docker/service_identities.yaml"
  _log_step "1/8 Remove service_identities.yaml entry for '${_agent}'"

  if [[ ! -f "$_sid_file" ]]; then
    _log_warn "  service_identities.yaml not found at ${_sid_file} — skipping"
    return 0
  fi

  # Check if an onboarded entry exists
  local _begin_marker="# BEGIN YSG-ONBOARD-${_agent}"
  if ! grep -qF "$_begin_marker" "$_sid_file" 2>/dev/null; then
    _log_info "  No sentinel entry for '${_agent}' in service_identities.yaml — already clean"
    return 0
  fi

  if _dry_print "python3: remove sentinel block for '${_agent}' from ${_sid_file}"; then
    return 0
  fi

  # Python rewriter — removes the sentinel-bracketed block
  python3 - "$_sid_file" "$_agent" <<'PYEOF'
import sys, re, os, tempfile
sid_file = sys.argv[1]
agent    = sys.argv[2]
content  = open(sid_file, encoding='utf-8').read()
begin    = '# BEGIN YSG-ONBOARD-' + agent
end      = '# END YSG-ONBOARD-'   + agent
b_pos = content.find(begin)
if b_pos == -1:
    sys.exit(0)  # already absent
# Find start of line
line_start = content.rfind('\n', 0, b_pos) + 1
e_pos = content.find(end, b_pos)
if e_pos == -1:
    print('[offboard] WARNING: BEGIN sentinel found but no END — removing from BEGIN to EOF', file=sys.stderr)
    new_content = content[:line_start]
else:
    end_line = content.find('\n', e_pos)
    end_line = (end_line + 1) if end_line != -1 else len(content)
    new_content = content[:line_start] + content[end_line:]
# Atomic write
dir_ = os.path.dirname(sid_file)
fd, tmp = tempfile.mkstemp(dir=dir_, prefix='.ysg-offboard-tmp-', suffix='.yaml')
try:
    os.write(fd, new_content.encode('utf-8'))
    os.close(fd); fd = -1
    orig_mode = oct(os.stat(sid_file).st_mode & 0o777)
    os.chmod(tmp, os.stat(sid_file).st_mode & 0o777)
    os.rename(tmp, sid_file)
except Exception as e:
    if fd != -1:
        os.close(fd)
    os.unlink(tmp)
    raise
PYEOF
  _log_info "  Removed service_identities.yaml entry for '${_agent}'"
}

# ---------------------------------------------------------------------------
# Step 2: Remove pki_ownership.sh tuple (via Python appender)
# ---------------------------------------------------------------------------
_offboard_step2_pki_ownership() {
  local _agent="$1"
  local _pki_sh="${WORK_DIR}/lib/pki_ownership.sh"
  local _appender="${WORK_DIR}/lib/pki_ownership_append.py"
  _log_step "2/8 Remove pki_ownership.sh tuple for '${_agent}'"

  if [[ ! -f "$_pki_sh" ]]; then
    _log_warn "  lib/pki_ownership.sh not found at ${_pki_sh} — skipping"
    return 0
  fi

  if [[ ! -f "$_appender" ]]; then
    _log_warn "  lib/pki_ownership_append.py not found — falling back to inline removal"
    # Inline Python fallback (same logic as appender remove)
    python3 - "$_pki_sh" "$_agent" <<'PYEOF'
import sys, re, os, tempfile
pki_file = sys.argv[1]
agent    = sys.argv[2]
content  = open(pki_file, encoding='utf-8').read()
begin    = '# BEGIN YSG-ONBOARD-' + agent
end      = '# END YSG-ONBOARD-'   + agent
b_pos = content.find(begin)
if b_pos == -1:
    sys.exit(0)
line_start = content.rfind('\n', 0, b_pos) + 1
e_pos = content.find(end, b_pos)
if e_pos == -1:
    sys.exit(0)
end_line = content.find('\n', e_pos)
end_line = (end_line + 1) if end_line != -1 else len(content)
new_content = content[:line_start] + content[end_line:]
dir_ = os.path.dirname(pki_file)
fd, tmp = tempfile.mkstemp(dir=dir_, prefix='.ysg-offboard-tmp-', suffix='.sh')
try:
    os.write(fd, new_content.encode('utf-8'))
    os.close(fd); fd = -1
    os.chmod(tmp, os.stat(pki_file).st_mode & 0o777)
    os.rename(tmp, pki_file)
except Exception:
    if fd != -1: os.close(fd)
    os.unlink(tmp)
    raise
PYEOF
    _log_info "  Removed pki_ownership.sh tuple for '${_agent}' (inline fallback)"
    return 0
  fi

  if _dry_print "python3 lib/pki_ownership_append.py remove --service ${_agent} --lib ${_pki_sh}"; then
    return 0
  fi

  local _rc=0
  python3 "$_appender" remove --service "$_agent" --lib "$_pki_sh" || _rc=$?
  case "$_rc" in
    0|2|3)
      _log_info "  pki_ownership.sh tuple removed (or already absent) for '${_agent}'"
      ;;
    *)
      _log_error "  pki_ownership_append.py remove failed (rc=${_rc})"
      return 1
      ;;
  esac
}

# ---------------------------------------------------------------------------
# Step 3: Remove Caddy include LINE
# S4 NOTE: This removes the import line and the snippet file.
# Sentinel-INSERT into Caddyfiles is Captain's scope (feat/p1-w3p2a-caddy-hardening).
# We remove by exact-string match only; do NOT modify surrounding Caddyfile structure.
# ---------------------------------------------------------------------------
_offboard_step3_caddy_snippet() {
  local _agent="$1"
  local _caddy_dir="${WORK_DIR}/docker/caddy"
  local _snippet="${_caddy_dir}/agents/${_agent}.caddy"
  _log_step "3/8 Remove Caddy snippet for '${_agent}'"

  # Remove the snippet file
  if [[ -f "$_snippet" ]]; then
    if _dry_print "rm ${_snippet}"; then :; else
      _three_tier_rm "$_snippet" || true
      _log_info "  Removed Caddy snippet: ${_snippet}"
    fi
  else
    _log_info "  Caddy snippet not present: ${_snippet}"
  fi

  # Remove the import line from any Caddyfile that references agents/<agent>.caddy
  # Exact-string match; Python file-rewrite (no sed -i).
  # TODO(S4-Captain): if Captain adds sentinel guards around the import block,
  #   update this to use sentinel removal instead of exact-string line removal.
  local _import_pattern="import agents/${_agent}.caddy"
  for _caddyfile in "${_caddy_dir}/Caddyfile" "${_caddy_dir}/Caddyfile.backoffice" "${_caddy_dir}/Caddyfile.gateway"; do
    if [[ ! -f "$_caddyfile" ]]; then
      continue
    fi
    if ! grep -qF "$_import_pattern" "$_caddyfile" 2>/dev/null; then
      continue
    fi
    if _dry_print "python3: remove '${_import_pattern}' from ${_caddyfile}"; then
      continue
    fi
    python3 - "$_caddyfile" "$_import_pattern" <<'PYEOF'
import sys, os, tempfile
caddyfile = sys.argv[1]
pattern   = sys.argv[2]
content   = open(caddyfile, encoding='utf-8').read()
lines     = content.splitlines(keepends=True)
new_lines = [l for l in lines if pattern not in l]
new_content = ''.join(new_lines)
if new_content == content:
    sys.exit(0)  # nothing to remove
dir_ = os.path.dirname(caddyfile) or '.'
fd, tmp = tempfile.mkstemp(dir=dir_, prefix='.ysg-offboard-caddy-', suffix='.tmp')
try:
    os.write(fd, new_content.encode('utf-8'))
    os.close(fd); fd = -1
    os.chmod(tmp, os.stat(caddyfile).st_mode & 0o777)
    os.rename(tmp, caddyfile)
except Exception:
    if fd != -1: os.close(fd)
    os.unlink(tmp)
    raise
PYEOF
    _log_info "  Removed '${_import_pattern}' from ${_caddyfile}"
  done
}

# ---------------------------------------------------------------------------
# Step 4: Remove compose override stanza
# docker/<agent>-compose.override.yml
# ---------------------------------------------------------------------------
_offboard_step4_compose_override() {
  local _agent="$1"
  local _override="${WORK_DIR}/docker/${_agent}-compose.override.yml"
  _log_step "4/8 Remove compose override for '${_agent}'"

  if [[ ! -f "$_override" ]]; then
    _log_info "  Compose override not present: ${_override}"
    return 0
  fi

  if _dry_print "rm ${_override}"; then
    return 0
  fi

  _three_tier_rm "$_override" || return 1
  _log_info "  Removed compose override: ${_override}"
}

# ---------------------------------------------------------------------------
# Step 5: Remove secrets and certs
# <agent>_client.key, <agent>_client.crt, <agent>_bootstrap_token
# ---------------------------------------------------------------------------
_offboard_step5_secrets() {
  local _agent="$1"
  local _secrets_dir="${WORK_DIR}/docker/secrets"
  _log_step "5/8 Remove secrets/certs for '${_agent}'"

  local _removed=0
  for _f in \
      "${_secrets_dir}/${_agent}_client.key" \
      "${_secrets_dir}/${_agent}_client.crt" \
      "${_secrets_dir}/${_agent}_bootstrap_token"; do
    if [[ -f "$_f" ]]; then
      if _dry_print "rm ${_f}"; then :; else
        _three_tier_rm "$_f" && _removed=$((_removed + 1)) || true
      fi
    fi
  done

  if [[ "$_removed" -gt 0 ]]; then
    _log_info "  Removed ${_removed} secret/cert file(s) for '${_agent}'"
  else
    _log_info "  No secret/cert files found for '${_agent}' — already clean"
  fi
}

# ---------------------------------------------------------------------------
# Step 6: Trigger PKI rotate-leaves
# So the remaining services get fresh leaves that no longer include the removed service.
# ---------------------------------------------------------------------------
_offboard_step6_pki_rotate() {
  local _agent="$1"
  _log_step "6/8 PKI rotate-leaves (remove '${_agent}' from leaf issuance)"

  if [[ "${YSG_RUNTIME:-docker}" == "k8s" ]]; then
    _log_info "  K8s runtime — PKI rotation is handled by mtls-bootstrap-job. Skipping."
    return 0
  fi

  if _dry_print "install.sh --pki-action=rotate-leaves (triggered by offboard)"; then
    return 0
  fi

  local _install_sh="${WORK_DIR}/install.sh"
  if [[ ! -f "$_install_sh" ]]; then
    _log_warn "  install.sh not found at ${_install_sh} — skipping PKI rotate-leaves"
    _log_warn "  Run manually: ./install.sh --pki-action=rotate-leaves"
    return 0
  fi

  # Source lib/pki_ownership.sh if available so _pki_run_issuer is accessible.
  # We call install.sh as a subprocess with --pki-action to avoid side-effects.
  # YSG_RUNTIME is passed through so the right runtime is used.
  local _rc=0
  YSG_RUNTIME="${YSG_RUNTIME:-docker}" \
  YSG_NO_LOG=true \
    bash "$_install_sh" --pki-action rotate-leaves 2>&1 | \
    while IFS= read -r _line; do
      _log_info "  pki: ${_line}"
    done || _rc=$?
  if [[ "$_rc" -ne 0 ]]; then
    _log_warn "  PKI rotate-leaves returned non-zero (rc=${_rc}) — manual rotation may be needed"
    _log_warn "  Run: ./install.sh --pki-action=rotate-leaves"
    return 0  # non-fatal: offboard continues; PKI rotation is advisory
  fi
  _log_info "  PKI rotate-leaves completed"
}

# ---------------------------------------------------------------------------
# Step 7: Remove Helm values
# helm/yashigani/values-<agent>.yaml
# helm/yashigani/values-<agent>-networkpolicy.yaml
# helm/yashigani/templates/agents/<agent>-policy-exception.yaml
# ---------------------------------------------------------------------------
_offboard_step7_helm() {
  local _agent="$1"
  local _helm_dir="${WORK_DIR}/helm/yashigani"
  _log_step "7/8 Remove Helm values for '${_agent}'"

  local _removed=0
  for _f in \
      "${_helm_dir}/values-${_agent}.yaml" \
      "${_helm_dir}/values-${_agent}-networkpolicy.yaml" \
      "${_helm_dir}/templates/agents/${_agent}-policy-exception.yaml"; do
    if [[ -f "$_f" ]]; then
      if _dry_print "rm ${_f}"; then :; else
        if rm -f "$_f" 2>/dev/null; then
          _removed=$((_removed + 1))
          _log_info "  [removed] ${_f}"
        else
          _log_warn "  Could not remove ${_f} — manual cleanup needed"
        fi
      fi
    fi
  done

  if [[ "$_removed" -gt 0 ]]; then
    _log_info "  Removed ${_removed} Helm artifact(s) for '${_agent}'"
  else
    _log_info "  No Helm artifacts found for '${_agent}' — already clean"
  fi
}

# ---------------------------------------------------------------------------
# Step 8: Write offboard ledger entry
# docker/var/offboard-ledger.log (gitignored)
# Format: ISO-8601 timestamp | agent | operator-uid | operator-user | runtime
# ---------------------------------------------------------------------------
_offboard_step8_ledger() {
  local _agent="$1"
  local _ledger_dir="${WORK_DIR}/docker/var"
  local _ledger_file="${_ledger_dir}/offboard-ledger.log"
  _log_step "8/8 Write offboard ledger entry"

  if _dry_print "ledger: offboard ${_agent} @ $(date -u +%Y-%m-%dT%H:%M:%SZ)"; then
    return 0
  fi

  mkdir -p "$_ledger_dir" 2>/dev/null || true

  local _ts
  _ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local _uid
  _uid="$(id -u 2>/dev/null || printf 'unknown')"
  local _user
  _user="$(id -un 2>/dev/null || printf 'unknown')"

  printf '%s | agent=%s | uid=%s | user=%s | runtime=%s\n' \
      "$_ts" "$_agent" "$_uid" "$_user" "${YSG_RUNTIME:-unknown}" \
      >> "$_ledger_file" 2>/dev/null || true
  chmod 0640 "$_ledger_file" 2>/dev/null || true

  _log_info "  Ledger entry written: ${_ledger_file}"
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
main() {
  if [[ $# -lt 1 ]]; then
    _offboard_usage
  fi

  local _agent="$1"

  # Validate name before any filesystem operations
  _validate_agent_name "$_agent" || exit 1

  _log_info "=== yashigani offboard: agent='${_agent}' ==="
  if [[ "${YSG_DRY_RUN:-false}" == "true" ]]; then
    _log_info "=== DRY RUN MODE — no changes will be made ==="
  fi

  # Resolve runtime
  _offboard_detect_runtime

  _log_info "  WORK_DIR=${WORK_DIR}"
  _log_info "  YSG_RUNTIME=${YSG_RUNTIME}"

  # Validate WORK_DIR is a yashigani repo root
  if [[ ! -f "${WORK_DIR}/install.sh" ]]; then
    _log_error "WORK_DIR '${WORK_DIR}' does not look like a yashigani repo root (install.sh not found)."
    _log_error "Set WORK_DIR=/path/to/yashigani or run from the repo root."
    exit 1
  fi

  # Execute all steps. Non-fatal steps continue on error; fatal steps exit.
  _offboard_step1_service_identity "$_agent"  || { _log_error "Step 1 failed"; exit 1; }
  _offboard_step2_pki_ownership    "$_agent"  || { _log_error "Step 2 failed"; exit 1; }
  _offboard_step3_caddy_snippet    "$_agent"  # non-fatal: Caddy reload not required
  _offboard_step4_compose_override "$_agent"  || { _log_error "Step 4 failed"; exit 1; }
  _offboard_step5_secrets          "$_agent"  # non-fatal: best-effort cleanup
  _offboard_step6_pki_rotate       "$_agent"  # non-fatal: advisory PKI rotation
  _offboard_step7_helm             "$_agent"  # non-fatal: Helm files may not exist
  _offboard_step8_ledger           "$_agent"  # non-fatal: ledger is advisory

  printf "\n"
  if [[ "${YSG_DRY_RUN:-false}" == "true" ]]; then
    _log_info "=== DRY RUN complete — no files were modified ==="
  else
    _log_info "=== offboard complete for agent='${_agent}' ==="
    _log_info "  Next steps:"
    _log_info "    1. Restart the stack to pick up the PKI rotation:"
    _log_info "       docker compose restart  (or: podman compose restart)"
    _log_info "    2. Verify no ${_agent} container is running:"
    _log_info "       docker ps | grep ${_agent}"
  fi
}

main "$@"
