#!/bin/sh
# entrypoint.sh — generate stunnel.conf from STUNNEL_* env vars and exec stunnel.
#
# Env var convention mirrors dweomer/stunnel so compose/Helm config is unchanged:
#   STUNNEL_ACCEPT    — local listen address:port (e.g. "5432" or "0.0.0.0:5432")
#   STUNNEL_CONNECT   — remote host:port to dial (e.g. "postgres:5432")
#   STUNNEL_CLIENT    — "yes" for TLS client mode (connecting to a TLS server)
#   STUNNEL_CRT       — path to client certificate PEM file (mTLS identity)
#   STUNNEL_KEY       — path to client private key PEM file
#   STUNNEL_CAFILE    — path to CA bundle PEM file (peer verification)
#   STUNNEL_VERIFY    — stunnel verify level (0=none,1=peer,2=peer+CA,3=peer+CA+CRL)
#                       default: 2 (verify peer cert + CA chain)
#   STUNNEL_SERVICE   — service name label in stunnel.conf (default: "proxy")
#   STUNNEL_DEBUG     — stunnel debug level 0-7 (default: 5)
#   STUNNEL_VERIFY_CHAIN — if "yes", add verifyChain=yes (full chain from root)
#   STUNNEL_CONF      — output path for generated conf (default: /etc/stunnel/stunnel.conf)
#
# stunnel.conf is written to STUNNEL_CONF (default /etc/stunnel/stunnel.conf),
# which must be on a writable tmpfs mount. Then stunnel is exec'd (no daemon fork).
set -eu

# Defaults
SERVICE="${STUNNEL_SERVICE:-proxy}"
ACCEPT="${STUNNEL_ACCEPT:?STUNNEL_ACCEPT must be set}"
CONNECT="${STUNNEL_CONNECT:?STUNNEL_CONNECT must be set}"
CLIENT="${STUNNEL_CLIENT:-no}"
CRT="${STUNNEL_CRT:-}"
KEY="${STUNNEL_KEY:-}"
CAFILE="${STUNNEL_CAFILE:-}"
VERIFY="${STUNNEL_VERIFY:-2}"
DEBUG_LEVEL="${STUNNEL_DEBUG:-5}"
VERIFY_CHAIN="${STUNNEL_VERIFY_CHAIN:-no}"
CONF="${STUNNEL_CONF:-/etc/stunnel/stunnel.conf}"

# Accept bare port numbers (match dweomer convention: "5432" → "0.0.0.0:5432")
case "$ACCEPT" in
    *:*) : ;;           # already host:port
    *) ACCEPT="0.0.0.0:${ACCEPT}" ;;
esac

# Ensure output directory is writable (comes from tmpfs mount)
CONF_DIR="$(dirname "$CONF")"
if [ ! -w "$CONF_DIR" ]; then
    echo "[entrypoint] ERROR: ${CONF_DIR} is not writable — is the tmpfs mount present?" >&2
    exit 1
fi

# Write global stunnel.conf header
cat > "$CONF" <<EOF
; Generated by letta-pg-stunnel/entrypoint.sh — DO NOT EDIT MANUALLY
; Regenerated on every container start from STUNNEL_* environment variables.

; Global settings
foreground = yes
debug = ${DEBUG_LEVEL}
pid = /var/run/stunnel/stunnel.pid
output = /dev/stderr

; TLS minimum version hardening (FIPS / PCI-DSS baseline)
sslVersionMin = TLSv1.2

; Non-root operation: UID/GID set at image build time (adduser stunnel, UID 101)
; Running as UID 101 already; setuid/setgid directives not needed.

; --- Service: ${SERVICE} ---
[${SERVICE}]
accept  = ${ACCEPT}
connect = ${CONNECT}
client  = ${CLIENT}
EOF

# Optional mTLS client certificate (required for letta→postgres mTLS)
if [ -n "$CRT" ]; then
    echo "cert    = ${CRT}" >> "$CONF"
fi
if [ -n "$KEY" ]; then
    echo "key     = ${KEY}" >> "$CONF"
fi

# Peer verification via CA bundle
if [ -n "$CAFILE" ]; then
    echo "CAfile  = ${CAFILE}" >> "$CONF"
fi

# Verify level: 2 = verify peer cert signed by CA (standard mTLS)
echo "verify  = ${VERIFY}" >> "$CONF"

# Full chain verification from root CA (defence-in-depth)
if [ "$VERIFY_CHAIN" = "yes" ]; then
    echo "verifyChain = yes" >> "$CONF"
fi

echo "[entrypoint] stunnel.conf written to ${CONF}:"
cat "$CONF" >&2

# Exec stunnel in foreground (no fork — container lifecycle = stunnel lifecycle)
exec stunnel "$CONF"
